services:
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    ports:
      - '3333:3000'
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}