version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    ports:
      - '3333:3000'
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${POSTGRES_DB_URL}
    depends_on:
      - db_postgres
    networks:
      - app-network
  db_postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
    volumes:
        - postgres:/data/postgres
volumes:
  postgres:

networks:
  app-network:
    driver: bridge
